tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'homebrew/fuse'
tap 'homebrew/science'

tap 'caskroom/cask'
tap 'caskroom/drivers'
tap 'caskroom/fonts'
tap 'caskroom/versions'

tap 'argon/mas'
tap 'neovim/neovim'
tap 'ravenac95/sudolikeaboss'

# UPDATE OS X APPS
brew 'bash'
brew 'binutils'
brew 'coreutils'
brew 'diffstat'
brew 'diffutils'
brew 'ed', args: ['with-default-names']
brew 'emacs'
brew 'expect'
brew 'file-formula'
brew 'findutils'
brew 'gawk'
brew 'git'
brew 'gnu-indent', args: ['with-default-names']
brew 'gnu-sed', args: ['with-default-names']
brew 'gnu-tar', args: ['with-default-names']
brew 'gnu-units', args: ['with-default-names']
brew 'gnu-which', args: ['with-default-names']
brew 'gpatch'
brew 'gperf'
brew 'grep', args: ['with-default-names']
brew 'groff'
brew 'gzip'
brew 'less'
brew 'make', args: ['with-default-names']
brew 'moreutils', args: ['without-parallel', 'force']
brew 'nano'
brew 'openssh'
brew 'openssl'
brew 'python'
brew 'rsync'
brew 'screen'
brew 'svn'
brew 'tidy-html5'
brew 'vim', args: ['override-system-vi']
brew 'wget'
brew 'zsh'

# APPS
brew 'ack'
brew 'archey'
brew 'argon/mas/mas'
brew 'aria2'
brew 'chruby'
brew 'diff-so-fancy'
brew 'flow'
brew 'graphicsmagick'
brew 'heroku-toolbelt'
brew 'htop'
brew 'httpie'
brew 'httrack'
brew 'hub'
brew 'jq'
brew 'mackup'
brew 'mas'
brew 'mongodb'
brew 'mysql'
brew 'neovim', args: ['HEAD']
brew 'parallel', args: ['force']
brew 'python3'
brew 'r'
brew 'ranger'
brew 'rethinkdb'
brew 'ruby-install', args: ['HEAD']
brew 's3cmd'
brew 'shellcheck'
brew 'sudolikeaboss'
brew 'syncthing'
brew 'tccutil'
brew 'the_platinum_searcher'
brew 'the_silver_searcher'
brew 'tmux'
brew 'trash'
brew 'tree'
brew 'watchman'
brew 'z'

# CASK APPS
cask '1password-beta'
cask 'aerial'
cask 'airmail-beta'
cask 'airserver'
cask 'airtool'
cask 'alfred'
cask 'apache-couchdb'
cask 'appcleaner'
cask 'asepsis'
cask 'atom-beta'
cask 'atom'
cask 'audiobookbinder'
cask 'balsamiq-mockups'
cask 'bartender'
cask 'bettertouchtool'
cask 'brackets'
cask 'brave'
cask 'calibre'
cask 'camtasia'
cask 'ccleaner'
cask 'charles-beta'
cask 'chromium'
cask 'codekit'
cask 'controlplane'
cask 'dash'
cask 'devonthink-pro-office'
cask 'discord'
cask 'docker'
cask 'dropbox-beta'
cask 'duet'
cask 'evernote'
cask 'fantastical'
cask 'filezilla'
cask 'firefox'
cask 'firefoxdeveloperedition'
cask 'flash-player'
cask 'flux'
cask 'fontprep'
cask 'free-ruler'
cask 'genymotion'
cask 'gisto'
cask 'github-desktop'
cask 'gitter'
cask 'glueprint'
cask 'glyphs'
cask 'google-chrome-canary'
cask 'google-chrome'
cask 'google-drive'
cask 'google-trends'
cask 'gpgtools'
cask 'grandperspective'
cask 'handbrake'
cask 'hipchat'
cask 'hyperswitch'
cask 'insomniax'
cask 'integrity'
cask 'istat-menus'
cask 'iterm2-beta'
cask 'itsycal'
cask 'java'
cask 'kaleidoscope'
cask 'karabiner-elements'
cask 'keka'
cask 'kismac'
cask 'kodi'
cask 'leech'
cask 'libreoffice'
cask 'limechat'
cask 'liteicon'
cask 'little-snitch'
cask 'livereload'
cask 'logitech-unifying'
cask 'macaw'
cask 'macid'
cask 'makemkv'
cask 'mamp'
cask 'mancy'
cask 'marked'
cask 'microsoft-office'
cask 'monodraw'
cask 'moom'
cask 'mplayerx'
cask 'mysqlworkbench'
cask 'navicat-premium'
cask 'ngrok'
cask 'nvalt'
cask 'nylas-n1'
cask 'obs'
cask 'omnifocus'
cask 'omnigraffle'
cask 'onyx'
cask 'opera-developer'
cask 'osxfuse'
cask 'parallels-desktop'
cask 'paw'
cask 'plex-media-player'
cask 'plex-media-server'
cask 'postgres'
cask 'postico'
cask 'psequel'
cask 'quickbooks-desktop'
cask 'rescuetime'
cask 'robofont'
cask 'robomongo'
cask 'rodeo'
cask 'rstudio'
cask 'sabnzbd'
cask 'safari-technology-preview'
cask 'screenhero'
cask 'scroll-reverser'
cask 'seil'
cask 'sketch-beta'
cask 'skype'
cask 'slack'
cask 'soundflower'
cask 'sourcetree'
cask 'spectacle'
cask 'steam'
cask 'stremio'
cask 'sublime-text'
cask 'switchresx'
cask 'synergy'
cask 'teamviewer'
cask 'textexpander'
cask 'totalfinder'
cask 'tower'
cask 'transmission'
cask 'twitterrific'
cask 'vagrant'
cask 'veracrypt'
cask 'virtualbox-extension-pack'
cask 'virtualbox'
cask 'viscosity'
cask 'vlc'
cask 'vmware-fusion'
cask 'webkit-nightly'
cask 'webstorm-eap'
cask 'wireshark'
cask 'xld'
cask 'xtrafinder'

# [Quick Look Plugins](https://github.com/sindresorhus/quick-look-plugins)
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'qlprettypatch'
cask 'quicklook-csv'
cask 'betterzipql'
cask 'qlimagesize'
cask 'webpquicklook'
cask 'suspicious-package'
cask 'quicklookase'
cask 'qlvideo'
cask 'provisionql'
cask 'quicklookapk'
cask 'quicklook-pat'

# FONTS
# brew cask search /powerline/ | grep font | xargs brew cask install
cask 'font-anonymice-powerline'
cask 'font-consolas-for-powerline'
cask 'font-dejavu-sans-mono-for-powerline'
cask 'font-droid-sans-mono-for-powerline'
cask 'font-fira-mono-for-powerline'
cask 'font-inconsolata-dz-for-powerline'
cask 'font-inconsolata-for-powerline'
cask 'font-inconsolata-g-for-powerline'
cask 'font-liberation-mono-for-powerline'
cask 'font-menlo-for-powerline'
cask 'font-meslo-for-powerline'
cask 'font-monofur-for-powerline'
cask 'font-roboto-mono-for-powerline'
cask 'font-source-code-pro-for-powerline'
cask 'font-ubuntu-mono-derivative-powerline'

cask 'font-hack'
cask 'font-monoid'

# DRIVERS
cask 'ax88179'

# NEED PREREQ
# XQUARTZ
cask 'fontforge'

# APP STORE
mas 'Day One Classic', id: 422304217
mas 'Deckset', id: 847496013
mas 'Pixelmator', id: 407963104
mas 'Reeder', id: 880001334
mas 'Xcode', id: 497799835

# PREREQ
brew 'macvim', args: ['with-custom-icons']
brew 'ntfs-3g'
brew 'sshfs'
cask 'xquartz'
